# Generated by Django 5.0.14 on 2025-12-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('intake', 'Intake'), ('testing', 'Testing'), ('ready', 'Ready for Sale'), ('sold', 'Sold'), ('recycled', 'Recycled'), ('returned', 'Returned to Client')], default='', max_length=50)),
                ('device_type', models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('server', 'Server'), ('tablet', 'Tablet'), ('phone', 'Phone'), ('other', 'Other')], default='', max_length=100)),
                ('cosmetic_grade', models.CharField(blank=True, choices=[('A', 'Grade A - Excellent'), ('B', 'Grade B - Good'), ('C', 'Grade C - Fair'), ('D', 'Grade D - Poor')], default='', max_length=20)),
                ('cosmetic_notes', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touch_type', models.CharField(choices=[('view', 'Viewed'), ('scan_upload', 'Hardware Scan Uploaded'), ('intake_update', 'Intake Information Updated'), ('drive_status', 'Drive Status Changed'), ('note', 'Note Added')], max_length=50)),
                ('touched_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touches', to='assets.asset')),
                ('touched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Touch',
                'verbose_name_plural': 'Asset Touches',
                'ordering': ['-touched_at'],
            },
        ),
        migrations.CreateModel(
            name='HardwareScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_json', models.JSONField()),
                ('summary', models.JSONField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user_notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_scans', to='assets.asset')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hardware Scan',
                'verbose_name_plural': 'Hardware Scans',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=200)),
                ('logicalname', models.CharField(blank=True, default='', max_length=100)),
                ('capacity_bytes', models.BigIntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('lshw', 'LSHW Scan'), ('manual', 'Manual Entry'), ('spreadsheet', 'Spreadsheet Import')], default='lshw', max_length=50)),
                ('status', models.CharField(choices=[('present', 'Present'), ('removed', 'Removed'), ('wiped', 'Wiped'), ('shredded', 'Shredded'), ('returned_to_client', 'Returned to Client')], default='present', max_length=50)),
                ('status_note', models.TextField(blank=True, default='')),
                ('status_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='assets.asset')),
                ('status_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drive_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drive',
                'verbose_name_plural': 'Drives',
                'ordering': ['id'],
                'unique_together': {('asset', 'serial')},
            },
        ),
    ]
