# Generated by Django 5.0.14 on 2025-12-22 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarescan',
            name='bundle_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hardwarescan',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hardwarescan',
            name='cosmetic_condition',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hardwarescan',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwarescan',
            name='intake_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hardwarescan',
            name='schema',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hardwarescan',
            name='tech_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='hardwarescan',
            index=models.Index(fields=['asset', 'generated_at'], name='asset_generated_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='hardwarescan',
            constraint=models.UniqueConstraint(fields=('asset', 'bundle_hash'), name='unique_asset_bundlehash'),
        ),
    ]
